FROM python:3.11-slim

WORKDIR /app

COPY requirements-rai-service.txt .
RUN pip install --no-cache-dir -r requirements-rai-service.txt

COPY responsible_ai ./responsible_ai
COPY responsible_ai_service ./responsible_ai_service

ENV PORT=8080

CMD exec uvicorn responsible_ai_service.app:app --host 0.0.0.0 --port ${PORT}
